%YAML:1.0

cam0:
  T_cam_imu:
    - [-0.014016761464218194, -0.9998584191316998, 0.009309784611549514, 
      0.062209362850855786]
    - [-0.0016421502690238455, -0.009287667842545096, -0.9999555202950482, 
      0.05138399868127757]
    - [0.9999004119113812, -0.014031426068108265, -0.0015117347472550402, 
      -0.0827378160943436]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.014016761464218158, -0.0016421502690238527, 0.9999004119113805, 
      0.08368593044056162]
    - [-0.9998584191316997, -0.00928766784254515, -0.014031426068108288, 
      0.061516863157855914]
    - [0.009309784611549458, -0.9999555202950482, -0.0015117347472550326, 
      0.05067747973571197]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /front/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam0r
cam1:
  T_cam_imu:
    - [-0.014016761464218194, -0.9998584191316998, 0.009309784611549514, 
      -0.07228202377682619]
    - [-0.0016421502690238455, -0.009287667842545096, -0.9999555202950482, 
      0.05138399868127757]
    - [0.9999004119113812, -0.014031426068108265, -0.0015117347472550402, 
      -0.0827378160943436]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.014016761464218158, -0.0016421502690238527, 0.9999004119113805, 
      0.08180079675520947]
    - [-0.9998584191316997, -0.00928766784254515, -0.014031426068108288, 
      -0.0729554820625284]
    - [0.009309784611549458, -0.9999555202950482, -0.0015117347472550326, 
      0.05192956557732431]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /front/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam1l
cam2:
  T_cam_imu:
    - [-0.999890735292991, 0.014344416582635916, -0.0035714406260498794, 
      0.08302382600200683]
    - [0.003622796649666627, 0.0035558222384001917, -0.9999871156533185, 
      0.05189196557190471]
    - [-0.014331532356198497, -0.9998907909572486, -0.003607400616862174, 
      -0.0715878531518118]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.9998907352929912, 0.003622796649666596, -0.014331532356198499, 
      0.08180079675520949]
    - [0.014344416582635926, 0.0035558222384002355, -0.9998907909572492, 
      -0.07295548206252846]
    - [-0.0035714406260499137, -0.9999871156533191, -0.003607400616862135, 
      0.05192956557732432]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /right/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam1r
cam3:
  T_cam_imu:
    - [-0.999890735292991, 0.014344416582635916, -0.0035714406260498794, 
      -0.05171089868492321]
    - [0.003622796649666627, 0.0035558222384001917, -0.9999871156533185, 
      0.05189196557190471]
    - [-0.014331532356198497, -0.9998907909572486, -0.003607400616862174, 
      -0.0715878531518118]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.9998907352929912, 0.003622796649666596, -0.014331532356198499, 
      -0.05291920618150372]
    - [0.014344416582635926, 0.0035558222384002355, -0.9998907909572492, 
      -0.07102279104347237]
    - [-0.0035714406260499137, -0.9999871156533191, -0.003607400616862135, 
      0.05144836850783776]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /right/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam2l
cam4:
  T_cam_imu:
    - [0.01449841752627851, 0.999775065358842, -0.01547948887918154, 
      0.07257045475200269]
    - [0.013063781164170951, -0.01566919606881743, -0.9997918853022639, 
      0.05101611623689873]
    - [-0.9998095486196016, 0.01429317953724633, -0.013288021214149404, 
      -0.0512103391298504]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.014498417526278286, 0.013063781164170877, -0.9998095486195984, 
      -0.052919206181503455]
    - [0.9997750653588383, -0.01566919606881734, 0.014293179537246455, 
      -0.07102279104347234]
    - [-0.015479488879181515, -0.9997918853022602, -0.013288021214149386, 
      0.05144836850783776]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /back/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam2r
cam5:
  T_cam_imu:
    - [0.01449841752627851, 0.999775065358842, -0.01547948887918154, 
      -0.06200867039109431]
    - [0.013063781164170951, -0.01566919606881743, -0.9997918853022639, 
      0.05101611623689873]
    - [-0.9998095486196016, 0.01429317953724633, -0.013288021214149404, 
      -0.0512103391298504]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.014498417526278286, 0.013063781164170877, -0.9998095486195984, 
      -0.05096802183485758]
    - [0.9997750653588383, -0.01566919606881734, 0.014293179537246455, 
      0.06352606259240275]
    - [-0.015479488879181515, -0.9997918853022602, -0.013288021214149386, 
      0.04936515243681521]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /back/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam3l
cam6:
  T_cam_imu:
    - [0.9998412250942471, -0.014918837435873035, 0.00974437743624294, 
      0.05142663171520949]
    - [0.009105920585101597, -0.042281071175456125, -0.9990642588095003, 
      0.052469020163478555]
    - [0.015316879981111515, 0.9989943640030409, -0.0421385082534515, 
      -0.06060133354040267]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.999841225094224, 0.009105920585101353, 0.015316879981111697, 
      -0.050968021834857574]
    - [-0.014918837435872167, -0.042281071175455154, 0.9989943640030188, 
      0.06352606259240148]
    - [0.009744377436242733, -0.9990642588094779, -0.04213850825345059, 
      0.04936515243681523]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /left/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam3r
cam7:
  T_cam_imu:
    - [0.9998412250942471, -0.014918837435873035, 0.00974437743624294, 
      -0.08324870362388702]
    - [0.009105920585101597, -0.042281071175456125, -0.9990642588095003, 
      0.052469020163478555]
    - [0.015316879981111515, 0.9989943640030409, -0.0421385082534515, 
      -0.06060133354040267]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.999841225094224, 0.009105920585101353, 0.015316879981111697, 
      0.08368593044056011]
    - [-0.014918837435872167, -0.042281071175455154, 0.9989943640030188, 
      0.06151686315785593]
    - [0.009744377436242733, -0.9990642588094779, -0.04213850825345059, 
      0.050677479735711954]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /left/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam0l
