%YAML:1.0

cam0:
  T_cam_imu:
    - [-0.008389550776860627, -0.9999300675986683, -0.008335187453476922, 
      0.06696039965749424]
    - [-0.009293836912478948, 0.008413091931791726, -0.9999214191523208, 
      0.003590791497222595]
    - [0.9999216169446518, -0.008311425646021503, -0.00936376903409823, 
      -0.059318247624857795]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.00838955077686075, -0.00929383691247894, 0.9999216169446514, 
      0.05990873798289838]
    - [-0.9999300675986689, 0.008413091931791784, -0.008311425646021381, 
      0.06643248809239179]
    - [-0.008335187453476873, -0.9999214191523212, -0.00936376903409824, 
      0.003593194442621234]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /front/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam0r
cam1:
  T_cam_imu:
    - [-0.008389550776860627, -0.9999300675986683, -0.008335187453476922, 
      -0.0674206715673527]
    - [-0.009293836912478948, 0.008413091931791726, -0.9999214191523208, 
      0.003590791497222595]
    - [0.9999216169446518, -0.008311425646021503, -0.00936376903409823, 
      -0.059318247624857795]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.00838955077686075, -0.00929383691247894, 0.9999216169446514, 
      0.05878134116240858]
    - [-0.9999300675986689, 0.008413091931791784, -0.008311425646021381, 
      -0.06793918554145095]
    - [-0.008335187453476873, -0.9999214191523212, -0.00936376903409824, 
      0.0024731030237631077]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /front/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam1l
cam2:
  T_cam_imu:
    - [-0.9999507865880879, 0.008866872063167533, -0.004450054120979625, 
      0.059391861840627565]
    - [0.004684037221010479, 0.02654481842122437, -0.9996366501936073, 
      0.004000303776236283]
    - [-0.00874552440831401, -0.9996082988825172, -0.02658504481891909, 
      -0.06733275247793565]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.999950786588088, 0.00468403722101051, -0.008745524408314045, 
      0.05878134116240859]
    - [0.008866872063167495, 0.026544818421224366, -0.9996082988825168, 
      -0.06793918554145091]
    - [-0.004450054120979598, -0.9996366501936074, -0.026585044818919084, 
      0.002473103023763107]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /right/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam1r
cam3:
  T_cam_imu:
    - [-0.9999507865880879, 0.008866872063167533, -0.004450054120979625, 
      -0.07518310479996879]
    - [0.004684037221010479, 0.02654481842122437, -0.9996366501936073, 
      0.004000303776236283]
    - [-0.00874552440831401, -0.9996082988825172, -0.02658504481891909, 
      -0.06733275247793565]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [-0.999950786588088, 0.00468403722101051, -0.008745524408314045, 
      -0.07578700258492144]
    - [0.008866872063167495, 0.026544818421224366, -0.9996082988825168, 
      -0.0667459265293437]
    - [-0.004450054120979598, -0.9996366501936074, -0.026585044818919084, 
      0.0018742371388834294]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /right/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam2l
cam4:
  T_cam_imu:
    - [0.010413381723773645, 0.9999309733212735, -0.005441513929405484, 
      0.06754071695483252]
    - [0.023918518714766038, -0.005689334462498744, -0.9996977222820221, 
      0.003306643538386802]
    - [-0.9996596750612503, 0.010280081037752572, -0.023976112910371366, 
      -0.0750301199229846]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.010413381723773617, 0.023918518714766114, -0.9996596750612521, 
      -0.07578700258492155]
    - [0.9999309733212751, -0.005689334462498765, 0.010280081037752634, 
      -0.0667459265293437]
    - [-0.005441513929405487, -0.9996977222820244, -0.023976112910371387, 
      0.0018742371388834294]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /back/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam2r
cam5:
  T_cam_imu:
    - [0.010413381723773645, 0.9999309733212735, -0.005441513929405484, 
      -0.06683377191758552]
    - [0.023918518714766038, -0.005689334462498744, -0.9996977222820221, 
      0.003306643538386802]
    - [-0.9996596750612503, 0.010280081037752572, -0.023976112910371366, 
      -0.0750301199229846]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.010413381723773617, 0.023918518714766114, -0.9996596750612521, 
      -0.07438770973835608]
    - [0.9999309733212751, -0.005689334462498765, 0.010280081037752634, 
      0.06761928691840212]
    - [-0.005441513929405487, -0.9996977222820244, -0.023976112910371387, 
      0.0011430364859274242]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /back/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam3l
cam6:
  T_cam_imu:
    - [0.9997945865905077, -0.008835341974792837, 0.018240651208277923, 
      0.07494901929943194]
    - [0.017990090310853506, -0.027653422850047855, -0.9994556742823975, 
      0.0043505606519558425]
    - [0.009334949111854993, 0.9995785236472734, -0.027488793866122345, 
      -0.06686496080867972]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.9997945865905098, 0.01799009031085358, 0.009334949111854918, 
      -0.07438770973835604]
    - [-0.00883534197479295, -0.027653422850047935, 0.9995785236472755, 
      0.06761928691840216]
    - [0.01824065120827793, -0.9994556742823996, -0.027488793866122387, 
      0.0011430364859274244]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /left/left/image_raw
  timeshift_cam_imu: 0.0
  frame: cam3r
cam7:
  T_cam_imu:
    - [0.9997945865905077, -0.008835341974792837, 0.018240651208277923, 
      -0.05937502038078983]
    - [0.017990090310853506, -0.027653422850047855, -0.9994556742823975, 
      0.0043505606519558425]
    - [0.009334949111854993, 0.9995785236472734, -0.027488793866122345, 
      -0.06686496080867972]
    - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
    - [0.9997945865905098, 0.01799009031085358, 0.009334949111854918, 
      0.05990873798289853]
    - [-0.00883534197479295, -0.027653422850047935, 0.9995785236472755, 
      0.06643248809239174]
    - [0.01824065120827793, -0.9994556742823996, -0.027488793866122387, 
      0.0035931944426212344]
    - [0.0, 0.0, 0.0, 1.0]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [320.0, 320.0, 320.0, 240.0]
  resolution: [640, 480]
  rostopic: /left/right/image_raw
  timeshift_cam_imu: 0.0
  frame: cam0l
