cam0:
  T_cam_imu:
  - [0.7019198807328844, -0.7122558711835499, 0.0002345133165137514, 
      0.005264952809378043]
  - [-0.00034417730274183267, -0.00066843694911628, -0.9999997173669747, 
      0.0036582185845781203]
  - [0.7122558266338841, 0.7019196016329842, -0.0007143314882070984, 
      -0.08929804653996805]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1, 3]
  camera_model: omni
  distortion_coeffs: [-0.1640104136309712, 1.1079917178782044, 
      -0.0009974088899274924, -0.00041808852238082767]
  distortion_model: radtan
  intrinsics: [3.2177333613138464, 1661.9801501644783, 1662.5009614874994, 
      555.4494087044619, 630.7107036421403]
  resolution: [1088, 1280]
  rostopic: /fisheye/left/image_raw
  timeshift_cam_imu: 0.00820612131856262
  T_cn_cnm1:
  - [0.0012177813265664078, 0.03210896344264552, -0.9994836324199088, 
      -0.09511122559376226]
  - [-0.007701631601452833, 0.9994550319248637, 0.032098660887341784, 
      0.0024955857531562824]
  - [0.9999696004775999, 0.007658565578743584, 0.001464409082160862, 
      -0.09481863980154508]
  - [0.0, 0.0, 0.0, 1.0]
cam1:
  T_cam_imu:
  - [-0.7176465722160794, -0.6962751904304627, -0.013574114244927493, 
      -0.0050865711721137935]
  - [-0.001254387339643337, 0.0207839922856769, -0.9997832025879766, 
      0.003958348939777956]
  - [0.6964063640568727, -0.7174739610994197, -0.015788959604565167, 
      -0.08964124891385265]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [-0.007807487345282582, 0.014286524134018382, -0.9998674604013816, 
      -0.09438393936049941]
  - [-0.01591846241857602, 0.9997694589594762, 0.014409423516977708, 
      0.0016715170499836103]
  - [0.9998428104935139, 0.016028853983718165, -0.00757826790150673, 
      -0.09564073569919015]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0, 2]
  camera_model: omni
  distortion_coeffs: [-0.18693699743090694, 1.046664529090386, 
      0.00013065568280514687, -0.0025110753450375183]
  distortion_model: radtan
  intrinsics: [3.1820560770133124, 1651.292998611214, 1651.2379235581757, 
      548.5968064788535, 629.9492625038849]
  resolution: [1088, 1280]
  rostopic: /fisheye/right/image_raw
  timeshift_cam_imu: 0.008191395936148517
cam2:
  T_cn_cnm1:
  - [0.01286198223753865, 0.006673366154923786, -0.9998950122873309, 
      -0.0957878198762168]
  - [0.0007505195827776953, 0.9999773830498664, 0.006683570086012641, 
      -0.00023217715883351724]
  - [0.9999169996221062, -0.0008364047471730268, 0.01285668284674546, 
      -0.094525453204129]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1, 3]
  camera_model: omni
  distortion_coeffs: [-0.16563034584708805, 1.0994847288365825, 
      -0.002420443612139874, -0.0015455427030177367]
  distortion_model: radtan
  intrinsics: [3.2089123942148317, 1657.315165757702, 1657.6983747934578, 
      562.3050002697363, 664.9064296125836]
  resolution: [1088, 1280]
  rostopic: /fisheye/bright/image_raw
  T_cam_imu:
  - [-0.7055719783963135, 0.7085818552082722, 0.008940792555090367, 
      -0.006194990068270026]
  - [0.0028615139673304605, 0.015465666545842388, -0.9998763047978013, 
      0.0031231411141765543]
  - [-0.7086324823487312, -0.7054591183250053, -0.012939757817643125, 
      -0.10076740207802909]
  - [0.0, 0.0, 0.0, 1.0]
cam3:
  T_cn_cnm1:
  - [-0.006333565723416534, 0.005895770325261698, -0.9999625622179557, 
      -0.09518757176533428]
  - [-0.04131349553958638, 0.9991272899984232, 0.006152517103390223, 
      0.0016708750545379313]
  - [0.9991261587164694, 0.041350916225383644, -0.006084463476228763, 
      -0.09483162772880711]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0, 2]
  camera_model: omni
  distortion_coeffs: [-0.17712064687722714, 1.0642689830438412, 
      0.0016810737414907318, -0.0008189646924026181]
  distortion_model: radtan
  intrinsics: [3.2022931943939215, 1654.2833070657282, 1654.49655149604, 
      543.0810826099137, 618.5330669686783]
  resolution: [1088, 1280]
  rostopic: /fisheye/bleft/image_raw
  T_cam_imu:
  - [0.7130916100472154, 0.7010360397677916, 0.006987605237783945, 
      0.005633707504114502]
  - [0.027648788010136316, -0.018162173101849203, -0.9994526902208964, 
      0.00442725410203179]
  - [-0.7005254457918273, 0.7128945268515584, -0.03233409011015911, 
      -0.10027894403489383]
  - [0.0, 0.0, 0.0, 1.0]
